.github/workflows/cd.yml, .github/workflows/ci.yml
=> feat: CI workflow 추가

.github/workflows/create_jira_issue.yml, commitlint.config.cjs
> [ci/cd]: create jira issue template
=> [ci/cd]: create jira issue template

eslint/tailwindcss.js, eslint/typescript.js, package.json, src/app/layout.tsx, src/features/main/components/Container/index.tsx, src/features/main/components/LoginModal/index.tsx, src/features/main/components/MenuItem/index.tsx, src/features/main/components/Navbar/index.tsx, src/features/main/components/RegisterModal/index.tsx, src/features/main/components/UserMenu/index.tsx, src/features/main/hooks/use-login-modal.ts, src/features/main/hooks/use-register-modal.ts, src/features/main/hooks/use-scroll-top.ts, src/shared/components/Avatar/index.tsx, src/shared/components/Heading/index.tsx, src/shared/components/Input/index.tsx, src/shared/components/Logo/index.tsx, src/shared/components/Modal/index.tsx, yarn.lock
> [CRAB-3]
[CRAB-3]: https://craftyourhabit.atlassian.net/browse/CRAB-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-3] Header 컴포넌트 구현 / 모달 컴포넌트 구현

next.config.mjs, package.json, src/app/academy/alert/page.tsx, src/app/academy/layout.tsx, src/app/academy/my/page.tsx, src/app/academy/setting/page.tsx, src/app/layout.tsx, src/app/page.tsx, src/features/academy/components/academy-tab.tsx, src/features/academy/components/tab-button.tsx, src/features/academy/my/api/get-participate-academy-list.mock.ts, src/features/academy/my/components/row-card.tsx, src/features/main/components/Navbar/index.tsx, src/features/main/components/UserMenu/index.tsx, src/shared/components/Button/index.tsx, src/shared/components/Flex/index.tsx, src/shared/components/MSWProvider/index.tsx, src/shared/constants/api.ts, src/shared/mocks/handler.ts, src/shared/mocks/http.ts, src/shared/mocks/index.ts, src/shared/styles/globals.css, yarn.lock
> [CRAB-6] My Academy Page Folder Structure
[CRAB-6]: https://craftyourhabit.atlassian.net/browse/CRAB-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-6] My Academy Page Folder Structure

src/features/main/SecondBanner/index.tsx, src/features/main/components/FifthBanner/index.tsx, src/features/main/components/FourthBanner/index.tsx, src/features/main/components/MainBanner/index.tsx, src/features/main/components/MainCard/index.tsx, src/features/main/components/MenuItem/index.tsx, src/features/main/components/ScholarshipCard/index.tsx, src/features/main/components/ThirdBanner/index.tsx, src/features/main/components/UserMenu/index.tsx
=> [CRAB-12] 모바일 화면 navbar 수정

eslint/tailwindcss.js, package.json, src/app/academy/(academy)/alert/page.tsx, src/app/academy/(academy)/my/components/academy-list/index.tsx, src/app/academy/(academy)/my/page.tsx, src/app/layout.tsx, src/features/academy/alert/components/ListRow.tsx, src/features/academy/my/components/Sidebar/side-bar.tsx, src/shared/apis/academy.ts, src/shared/components/Flex/index.tsx, src/shared/components/Skeleton/Skeleton.tsx, src/shared/constants/query-keys.ts, src/shared/hooks/academy/useGetInfiniteAcademyList.ts, src/shared/types/acadmy.ts, tailwind.config.ts, yarn.lock
> [CRAB-17]
@hijjoy SSR 무한스크롤 구현했으니, 코드 참고해주세용~!!
CSR 방식과 살짝 다릅니다, dehydrate 해줘야 하더라고요....
[CRAB-17]: https://craftyourhabit.atlassian.net/browse/CRAB-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-17] SSR dehydrate 무한스크롤 구현, 반응형 에러 수정, Skeleton UI 구현

next.config.mjs, src/app/academy/(workspace)/[id]/challenge/page.tsx, src/app/academy/(workspace)/[id]/dashboard/layout.tsx, src/app/academy/(workspace)/[id]/layout.tsx, src/app/academy/(workspace)/[id]/my-challenge/[studentId]/page.tsx, src/app/academy/(workspace)/[id]/my-challenge/components/challenge-list/index.tsx, src/features/academy/(workspace)/api/get-academy-profile.ts, src/features/academy/(workspace)/components/challenge-card/index.tsx, src/features/academy/(workspace)/components/challenge-list/index.tsx, src/features/academy/(workspace)/components/my-challenge-card/index.tsx, src/features/academy/(workspace)/components/my-challenge-list/index.tsx, src/features/academy/(workspace)/components/state-label/index.tsx, src/features/academy/(workspace)/components/workspace-tab.tsx, src/features/academy/(workspace)/utils/challengeState.ts, src/shared/apis/challenge.ts, src/shared/constants/query-keys.ts, src/shared/hooks/challenge/useGetInfiniteStudentChallengeList.ts, src/shared/hooks/challenge/useGetInfiniteTeacherChallengeList.ts, src/shared/types/acadmy.ts, src/shared/utils/date.ts
#37 
학생 자신이 참여한 챌린지
원장/강사 만든 챌린지 
env에 
NEXT_PUBLIC_S3_HOSTNAME
NEXT_PUBLIC_S3_IMAGES 
를 추가하였습니다.
next.config.mjs에 next/Image사용을 위해 
hostname: process.env.NEXT_PUBLIC_S3_HOSTNAME 로 추가했습니다
=> [CRAB-18] 아카데미 페이지 ui 수정

eslint/react.js, src/features/space/enroll/components/form.tsx, src/shared/apis/academy.ts, src/shared/components/AddressSearch/address-search.tsx
=> [CRAB-19] 학원 등록하기 API 연결, 학원 생성 버그 수정

src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx, src/app/academy/(workspace)/[id]/members/detail/page.tsx, src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx, src/features/academy/(workspace)/api/post-academy-challenges.ts, src/features/main/components/RegisterModal/index.tsx, src/shared/apis/academy.ts, src/shared/apis/challenge.ts, src/shared/constants/query-keys.ts, src/shared/hooks/academy/useGetInfiniteAcademyMemberDetailList.ts, src/shared/hooks/images/use-get-presigned-url.ts, src/shared/libs/axios-instance.ts, src/shared/types/acadmy.ts, src/shared/utils/authOptions.ts
기존 폴더 삭제하고, url 옮겼으니 확인 부탁드립니다. /member/detail
=> [CRAB-23] (원장) 학생 리스트 조회, 학생 리스트 화면 구현

src/app/academy/(workspace)/[id]/members/instructor/components/InstructorDetailList/index.tsx, src/app/academy/(workspace)/[id]/members/instructor/page.tsx, src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx, src/shared/apis/challenge.ts, src/shared/constants/query-keys.ts, src/shared/hooks/academy/useGetInfiniteAcademyInstructorList.ts, src/shared/types/acadmy.ts
> [CRAB-24] (원장) 학원 전체 강사리스트 조회, 강사 리스트 화면 구현
[CRAB-24]
[CRAB-24]: https://craftyourhabit.atlassian.net/browse/CRAB-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRAB-24]: https://craftyourhabit.atlassian.net/browse/CRAB-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-24] (원장) 학원 전체 강사리스트 조회, 강사 리스트 화면 구현

src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx, src/app/academy/(workspace)/[id]/members/student/page.tsx, src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx, src/shared/apis/challenge.ts, src/shared/constants/query-keys.ts, src/shared/hooks/academy/useGetInfiniteAcademyStudentList.ts, src/shared/types/acadmy.ts
> [CRAB-25] (원장, 강사) 학원 전체, 학생 기본 프로필 리스트 조회
[CRAB-25]: https://craftyourhabit.atlassian.net/browse/CRAB-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-25] (원장, 강사) 학원 전체, 학생 기본 프로필 리스트 조회

src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx, src/app/academy/(workspace)/[id]/members/detail/page.tsx, src/app/academy/(workspace)/[id]/members/instructor/components/InstructorDetailList/index.tsx, src/app/academy/(workspace)/[id]/members/instructor/page.tsx, src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx, src/app/academy/(workspace)/[id]/members/student/page.tsx, src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx, src/features/academy/(workspace)/api/post-academy-challenges.ts, src/features/main/components/RegisterModal/index.tsx, src/shared/apis/academy.ts, src/shared/apis/challenge.ts, src/shared/constants/query-keys.ts, src/shared/hooks/academy/useGetInfiniteAcademyInstructorList.ts, src/shared/hooks/academy/useGetInfiniteAcademyMemberDetailList.ts, src/shared/hooks/academy/useGetInfiniteAcademyStudentList.ts, src/shared/hooks/images/use-get-presigned-url.ts, src/shared/libs/axios-instance.ts, src/shared/types/acadmy.ts, src/shared/utils/authOptions.ts
> [Deploy] 2024년 10월 26일 Daily Deploy
=> [Deploy] 2024년 10월 26일 Daily Deploy

src/app/academy/(workspace)/[id]/invitation/components/Invitation/index.tsx, src/app/academy/(workspace)/[id]/invitation/page.tsx, src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx, src/shared/apis/invitation.ts, src/shared/constants/query-keys.ts, src/shared/types/invitation.ts
> [CRAB-29] 가입 코드 페이지 / 기능 구현
[CRAB-29]: https://craftyourhabit.atlassian.net/browse/CRAB-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-29] 가입 코드 페이지 / 기능 구현

src/app/academy/(workspace)/[id]/challenge/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/challenge/components/StudentTableContent/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/BarChart/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/DashboardCard/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/DashboardChallengeTable/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/DonutChart/index.tsx, src/app/academy/(workspace)/[id]/dashboard/layout.tsx, src/app/academy/(workspace)/[id]/dashboard/page.tsx, src/app/academy/(workspace)/[id]/market/components/ChallengeCard/index.tsx, src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx, src/features/academy/(workspace)/components/challenge-card/index.tsx, src/features/academy/(workspace)/components/challenge/challenge-student-list/index.tsx, src/features/academy/(workspace)/components/dashboard/academy-title/index.tsx, src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx, src/features/academy/(workspace)/components/dashboard/chart-view/index.tsx, src/features/academy/(workspace)/components/my-challenge-card/index.tsx, src/features/main/components/UserMenu/index.tsx, src/shared/apis/academy.ts, src/shared/apis/challenge.ts, src/shared/constants/query-keys.ts, src/shared/hooks/challenge/useGetInfiniteAllChallengeContents.ts, src/shared/types/acadmy.ts
=> [CRAB-30] 대시보드 통계 연결 & 학생 대시보드 연결 

src/app/academy/(academy)/my/components/academy-list/index.tsx, src/app/academy/(academy)/my/page.tsx, src/app/academy/(workspace)/[id]/setting/components/revoke-button/index.tsx, src/app/api/academy/list/route.ts, src/app/api/auth/login/route.ts, src/app/api/auth/logout/route.ts, src/app/api/auth/profile/route.ts, src/features/main/components/LoginModal/index.tsx, src/features/main/components/UserMenu/index.tsx, src/features/space/enroll/components/form.tsx, src/shared/apis/academy.ts, src/shared/apis/challenge.ts, src/shared/apis/fetch-data.ts, src/shared/apis/set-auth-cookie.ts, src/shared/constants/query-keys.ts, src/shared/hooks/challenge/useCreateChallengeContent.ts, src/shared/hooks/main/useGetProfile.ts, src/shared/types/auth.ts
#79 
로그인 여부 파악해서 프로필 변경하는 부분 일단 useQuery로 처리했습니다 
이후 변경이 필요하면 변경하겠습니다
=> [CRAB-35] 로그인 쿠키 방식으로 변경 

eslint/default.js, src/app/api/academy/enroll/route.ts, src/features/space/enroll/apis/use-enroll-academy.ts, src/features/space/enroll/components/form.tsx, src/shared/apis/fetch-data.ts, src/shared/constants/api-error-message.ts, src/shared/types/acadmy.ts, yarn.lock
=> [CRAB-37] 서버 에러를 받아오지 못하는 현상과, custom fetch hook 수정

src/shared/components/ChannelTalk/index.tsx, src/shared/components/QueryProvider/index.tsx
> [CRAB-39] Channel Talk 연결
[CRAB-39]: https://craftyourhabit.atlassian.net/browse/CRAB-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-39] Channel Talk 연결

src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx, src/app/academy/(workspace)/[id]/dashboard/create/components/First.tsx, src/features/academy/(workspace)/components/dashboard/ChallengeMenu/index.tsx, src/features/main/components/UserMenu/index.tsx, src/shared/components/Button/index.tsx, src/shared/components/CheckBox/index.tsx, src/shared/utils/style.ts, tailwind.config.ts
=> [CRAB-40] 챌린지 생성 오류 메세지 및 ui 수정

src/app/academy/(academy)/my/components/academy-list/index.tsx, src/app/academy/(academy)/my/layout.tsx, src/app/academy/(academy)/my/page.tsx, src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx, src/shared/components/Skeleton/Skeleton.tsx
> [CRAB-42] 내 학원 목록, 디자인 변경 (AnimateCard, AnimateCardSkeleton 공용컴포넌트 구현)
[CRAB-42]: https://craftyourhabit.atlassian.net/browse/CRAB-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-42] 내 학원 목록, 디자인 변경 (AnimateCard, AnimateCardSkeleton 공용컴포넌트 구현)

eslint/default.js, src/app/academy/(academy)/my/components/academy-list/index.tsx, src/app/academy/(academy)/my/components/invitation-modal/components/Tab.tsx, src/app/academy/(academy)/my/components/invitation-modal/index.tsx, src/app/academy/(academy)/my/hooks/use-invitation-modal.ts, src/app/academy/(academy)/my/layout.tsx, src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx, src/app/api/invitation/route.ts, src/shared/apis/invitation.ts, src/shared/components/Modal/index.tsx, src/shared/components/Skeleton/Skeleton.tsx, src/shared/hooks/invitation/useEnrollInvitation.ts, src/shared/mocks/http.ts, src/shared/types/invitation.ts
> [CRAB-43] 학원 가입 신청 모달 패널 구현
[CRAB-43]: https://craftyourhabit.atlassian.net/browse/CRAB-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-43] 학원 가입 신청 모달 패널 구현

src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/@modal/(.)[releasedId]/page.tsx, src/app/academy/(workspace)/[id]/public-challenge/@modal/default.tsx, src/app/academy/(workspace)/[id]/public-challenge/[releasedId]/page.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/layout.tsx, src/app/api/challenge/public/route.ts, src/features/academy/(workspace)/components/state-label/index.tsx, src/shared/apis/market.ts, src/shared/hooks/market/useApplyChallenge.ts, src/shared/types/market.ts, src/shared/types/public.ts
=> [CRAB-47] 공개 챌린지 신청 및 상세보기

src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeFeed/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/feed/page.tsx, src/app/api/challenge/student/logs/route.ts, src/features/academy/(workspace)/components/workspace-tab.tsx, src/shared/apis/challenge.ts, src/shared/constants/query-keys.ts, src/shared/constants/tab-menu.ts, src/shared/hooks/challenge/useGetInfiniteFeedChallengeContents.ts
=> [CRAB-48] 학생 챌린지 feed, my 챌린지 로딩 수정

src/app/academy/(academy)/my/components/academy-list/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(principal)/DashBoardUI/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/PlusChallengeCard/index.tsx, src/app/academy/(workspace)/[id]/dashboard/page.tsx, src/app/api/challenge/list/route.ts, src/shared/apis/challenge.ts, src/shared/hooks/challenge/useGetInfiniteTeacherChallengeList.ts, src/shared/hooks/useDebounce.ts
=> [CRAB-51] 원장/강사 대시보드 수정

src/app/academy/(workspace)/[id]/dashboard/components/(student)/DashBoardUI/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentAllChallengeContents/index.tsx, src/app/academy/(workspace)/[id]/dashboard/page.tsx, src/app/api/challenge/list/route.ts, src/app/api/challenge/student/list/route.ts, src/shared/apis/challenge.ts, src/shared/constants/tab-menu.ts, src/shared/hooks/challenge/useGetInfiniteStudentChallengeList.ts
=> [CRAB-52] 학생 대시보드 검색어 및 카테고리 처리

src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx, src/app/academy/(workspace)/[id]/dashboard/create/components/First.tsx, src/app/academy/(workspace)/[id]/dashboard/create/components/Second.tsx, src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx, src/app/academy/(workspace)/[id]/dashboard/create/page.tsx, src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/market/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx, src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx, src/app/academy/(workspace)/[id]/market/components/Release/First.tsx, src/app/academy/(workspace)/[id]/market/components/Release/Second.tsx, src/shared/apis/challenge.ts, src/shared/components/BoxContainer/index.tsx, src/shared/components/ProgressBar/index.tsx, src/shared/hooks/market/useRelease.ts, src/shared/hooks/use-step-progress.ts, src/shared/hooks/useHandleStepChallenge.ts, src/shared/types/acadmy.ts, src/shared/types/market.ts
#123 
`원장/강사` 
* 챌린지를 생성할 때 원래 내용과 다른 또는 추가할 내용이 있는 경우 적어달라고 안내 문구 
* 단 null로 보냅니다.
`학생` 
* 챌린지 description 조회 
* 챌린지 description 추가 및 UI step으로 수정 (페이지 & 모달 모두 수정)
description 필드를 추가하면서.. 챌린지 생성 모달&페이지를 두 step 으로 변경하면서 수정사항이 좀 많습니다...
=> [CRAB-54] 배포 챌린지 description 추가

src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeFeed/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/feed/page.tsx
#122 
챌린지 상세 ui도 구현하려 했으나 ...
api 나오면 구현하겠습니다.
=> [CRAB-53] 챌린지 피드 ui 수정

src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx, src/shared/types/public.ts
#126 
- 2xl 4개로 변경
- 모달 ui 수정 등.. ui 수정 
=> [CRAB-55] 공개 챌린지 UI 수정

src/app/api/auth/profile/route.ts, src/app/profile/@sidebar/page.tsx, src/app/profile/components/LinkBox/index.tsx, src/app/profile/components/ProfileBox/index.tsx, src/app/profile/components/ProfileEditForm/index.tsx, src/app/profile/delete/page.tsx, src/app/profile/layout.tsx, src/app/profile/page.tsx, src/app/profile/password/page.tsx, src/features/main/components/UserMenu/index.tsx, src/shared/apis/invitation.ts, src/shared/apis/profile.ts, src/shared/components/Avatar/index.tsx, src/shared/enums/auth.ts, src/shared/hooks/main/useGetProfile.ts, src/shared/hooks/profile/useEditProfile.ts, src/shared/types/auth.ts, tailwind.config.ts
=> [CRAB-49] 마이페이지 구현 

src/app/academy/(workspace)/[id]/dashboard/page.tsx, src/app/academy/(workspace)/[id]/layout.tsx
> [CRAB-56] Refresh Token 로직 수정
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
> 해당 기능이 개발될 브랜치 명을 알려주세요!
[CRAB-56] 
[CRAB-56]: https://craftyourhabit.atlassian.net/browse/CRAB-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRAB-56]: https://craftyourhabit.atlassian.net/browse/CRAB-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-56] Refresh Token 로직 수정

src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeFeed/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContents/index.tsx, src/app/academy/(workspace)/[id]/dashboard/page.tsx, src/app/academy/(workspace)/[id]/feed/[feedId]/@comment/page.tsx, src/app/academy/(workspace)/[id]/feed/[feedId]/@detail/page.tsx, src/app/academy/(workspace)/[id]/feed/[feedId]/layout.tsx, src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/feed/components/CommentForm/index.tsx, src/shared/types/acadmy.ts, tailwind.config.ts
#136 
현재는 ui 구성만 되어있습니다 (+ 상세 api 는 연결)
=> [CRAB-58] 챌린지 피드 상세 

src/app/space/enroll/page.tsx, src/features/space/enroll/components/form.tsx, src/features/space/enroll/components/phone-input.tsx, src/shared/components/AddressSearch/address-search.tsx, src/shared/components/Footer/index.tsx
> [CRAB-62]
[CRAB-62]: https://craftyourhabit.atlassian.net/browse/CRAB-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-62] 학원 생성 신청 (이메일 인증 포함) 구현, 번호 양식 자동화 인풋 생성.

src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx, src/app/academy/(workspace)/[id]/feed/components/CommentIcon/index.tsx, src/app/academy/(workspace)/[id]/feed/components/CommentList/index.tsx, src/app/api/comment/block/route.ts, src/shared/apis/comments.ts, src/shared/hooks/comments/useBlockComment.ts, src/shared/types/comment.ts
=> [CRAB-66] 댓글 차단 api 연결

src/app/academy/(workspace)/[id]/dashboard/page.tsx
=> [CRAB-68] 대시보드 학원 정보 변경

src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx, src/app/api/manage/academy/challenge/route.ts, src/app/api/manage/academy/route.ts, src/app/api/manage/instructor/edit/route.ts, src/app/api/manage/instructor/revoke/route.ts, src/app/api/manage/student/edit/route.ts, src/app/api/manage/student/revoke/route.ts, src/shared/types/manage.ts
> [CRAB-70] 학원 세팅 관련 Route Handler 제작
[CRAB-70]: https://craftyourhabit.atlassian.net/browse/CRAB-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-70] 학원 세팅 관련 Route Handler 제작

src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx, src/app/api/comment/route.ts, src/shared/apis/comments.ts, src/shared/components/Button/index.tsx, src/shared/components/SmallModal/index.tsx, src/shared/hooks/comments/useDeleteComment.ts, src/shared/types/comment.ts
=> [CRAB-69] 댓글 삭제하기

src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx, src/shared/hooks/challenge/useCreateChallengeContent.ts
=> [CRAB-71] 학생 자신의 챌린지 상세 UI 수정 

eslint/default.js, src/shared/apis/academy.ts, src/shared/apis/fetch-data.ts, src/shared/constants/query-keys.ts, src/shared/hooks/academy/useManageAcademy.ts
[CRAB-74] useManageAcademy Hook 생성
[CRAB-74]: https://craftyourhabit.atlassian.net/browse/CRAB-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-74] useManageAcademy Hook 생성

src/app/academy/(workspace)/[id]/setting/components/SettingBar/index.tsx, src/app/academy/(workspace)/[id]/setting/components/SettingInfo/index.tsx, src/app/academy/(workspace)/[id]/setting/layout.tsx, src/app/academy/(workspace)/[id]/setting/management/academy/page.tsx, src/app/academy/(workspace)/[id]/setting/management/instructor/page.tsx, src/app/academy/(workspace)/[id]/setting/management/student/page.tsx, src/app/academy/(workspace)/[id]/setting/page.tsx, src/shared/components/ProfileCard/index.tsx
=> [CRAB-73] 학원 설정페이지 구현

src/app/profile/components/DeleteForm/index.tsx, src/shared/hooks/main/useGetProfile.ts
=> [CRAB-72] 마이페이지 탈퇴 모달 수정

src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx
=> [CRAB-75] 챌린지 상세 레이아웃 수정

src/app/academy/(academy)/my/layout.tsx, src/app/academy/(academy)/my/page.tsx, src/app/academy/(workspace)/[id]/layout.tsx, src/middleware.ts
[CRAB-77] Protected Route 적용
[CRAB-77]: https://craftyourhabit.atlassian.net/browse/CRAB-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-77] Protected Route 적용

src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/BestStudentTableContent/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx, src/app/api/auth/login/route.ts, src/shared/components/ProfileCard/index.tsx, src/shared/utils/number.ts
> [CRAB-78]
[CRAB-78]: https://craftyourhabit.atlassian.net/browse/CRAB-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-78] 포인트가 노출되지 않는 현상 해결, 천 단위 숫자 포맷팅

src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx, src/app/academy/(workspace)/[id]/members/instructor/components/InstructorDetailList/index.tsx, src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx, src/app/academy/(workspace)/[id]/setting/components/InstructorList/index.tsx, src/app/academy/(workspace)/[id]/setting/components/InstructorStudentList/index.tsx, src/app/academy/(workspace)/[id]/setting/components/PrincipalStudentList/index.tsx, src/app/academy/(workspace)/[id]/setting/layout.tsx, src/app/academy/(workspace)/[id]/setting/management/instructor/[memberId]/page.tsx, src/app/academy/(workspace)/[id]/setting/management/instructor/page.tsx, src/app/academy/(workspace)/[id]/setting/management/student/[memberId]/page.tsx, src/app/academy/(workspace)/[id]/setting/management/student/[studentId]/page.tsx, src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx, src/app/academy/(workspace)/[id]/setting/management/student/page.tsx, src/app/api/academy/manage/admin/students/route.ts, src/features/academy/(workspace)/components/dashboard/Students/index.tsx, src/shared/components/FramerScale/index.tsx, src/shared/components/ProfileCard/index.tsx, src/shared/components/Textarea/index.tsx, src/shared/hooks/academy/useGetInfiniteAcademyInstructorList.ts, src/shared/types/acadmy.ts
=> [CRAB-76] 설정 페이지 학생/강사 관리 연결

src/app/profile/components/EmailForm/index.tsx, src/app/profile/components/PasswordForm/index.tsx, src/app/profile/components/ProfileEditForm/index.tsx, src/features/space/enroll/components/form.tsx
> [CRAB-80] 학원 등록, 서버 변경사항 반영 및 UI 변경, 이메일 인증하기 플로우 변경
[CRAB-80]: https://craftyourhabit.atlassian.net/browse/CRAB-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-80] 학원 등록, 서버 변경사항 반영 및 UI 변경, 이메일 인증하기 플로우 변경

src/app/academy/(workspace)/[id]/setting/components/AcademyProfileForm/index.tsx, src/app/academy/(workspace)/[id]/setting/management/academy/components/AcademyEditForm/index.tsx, src/app/academy/(workspace)/[id]/setting/management/academy/page.tsx, src/app/academy/(workspace)/[id]/setting/management/instructor/[memberId]/page.tsx, src/app/academy/(workspace)/[id]/setting/management/instructor/components/InstructorDetail/index.tsx, src/app/academy/(workspace)/[id]/setting/management/student/[memberId]/page.tsx, src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx, src/app/academy/(workspace)/[id]/setting/page.tsx, src/app/api/academy/profile/instructors/route.ts, src/app/api/academy/profile/route.ts, src/shared/apis/academy.ts, src/shared/components/Textarea/index.tsx, src/shared/constants/query-keys.ts, src/shared/hooks/academy/useManageAcademy.ts, src/shared/types/acadmy.ts
[CRAB-81] 학원 설정 API 연결 및, UI 초안 구현
[CRAB-81]: https://craftyourhabit.atlassian.net/browse/CRAB-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-81] 학원 설정 API 연결 및, UI 초안 구현

src/shared/styles/globals.css
=> [CRAB-82] 사파리 글씨 두께 해결

src/app/academy/(workspace)/[id]/setting/page.tsx, src/app/api/auth/password/route.ts, src/app/layout.tsx, src/app/profile/components/EmailForm/index.tsx, src/app/profile/components/PasswordForm/index.tsx, src/features/main/components/LoginModal/index.tsx, src/features/main/components/PasswordChangeModal/index.tsx, src/features/main/hooks/use-password-change-modal.ts, src/shared/apis/auth.ts, src/shared/apis/profile.ts, src/shared/components/Input/index.tsx, src/shared/components/Modal/index.tsx, src/shared/hooks/auth/queries/usePasswordChange.ts, src/shared/hooks/email/useVerifyCode.ts, src/shared/types/auth.ts, src/shared/utils/schema.ts
[CRAB-89] 로그인 / 비로그인시 비밀번호 변경 관련, 서버 변경 및 추가사항 반영.
[CRAB-89]: https://craftyourhabit.atlassian.net/browse/CRAB-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-89] 로그인 / 비로그인시 비밀번호 변경 관련, 서버 변경 및 추가사항 반영.

src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx, src/app/academy/(workspace)/[id]/dashboard/page.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/page.tsx, src/app/api/auth/password/route.ts, src/app/layout.tsx, src/app/profile/components/EmailForm/index.tsx, src/app/profile/components/PasswordForm/index.tsx, src/features/main/components/AcademyMenu/index.tsx, src/features/main/components/AcademyProfileMenu/index.tsx, src/features/main/components/LoginModal/index.tsx, src/features/main/components/PasswordChangeModal/index.tsx, src/features/main/components/UserMenu/index.tsx, src/features/main/hooks/use-password-change-modal.ts, src/shared/apis/auth.ts, src/shared/apis/profile.ts, src/shared/components/Input/index.tsx, src/shared/components/Modal/index.tsx, src/shared/hooks/auth/queries/usePasswordChange.ts, src/shared/hooks/email/useVerifyCode.ts, src/shared/types/auth.ts, src/shared/utils/schema.ts
=> [CRAB-87] 반응형 수정

src/app/academy/(workspace)/[id]/setting/components/AcademyProfileForm/index.tsx, src/app/academy/(workspace)/[id]/setting/components/SettingBar/index.tsx, src/app/academy/(workspace)/[id]/setting/management/instructor/components/InstructorDetail/index.tsx, src/app/academy/(workspace)/[id]/setting/management/invitation/components/Invitation/index.tsx, src/app/academy/(workspace)/[id]/setting/management/invitation/page.tsx, src/features/main/components/AcademyProfileMenu/index.tsx, src/shared/hooks/academy/useManageAcademy.ts, src/shared/utils/academyRole.ts
#215 
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
- 쿼리키가 안맞아서 변경이 안되는 이슈가 있어, 수정했습니다. 
=> [CRAB-90] 설정 페이지 변경

src/app/academy/(workspace)/[id]/dashboard/components/(student)/DashBoardUI/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentAllChallengeContents/index.tsx, src/app/error.tsx, src/app/my/components/invitation-modal/components/Tab.tsx, src/shared/components/Modal/index.tsx
[CRAB-88] 반응형 모달 수정, ErrorBoundary 설정 및 디자인
[CRAB-88]: https://craftyourhabit.atlassian.net/browse/CRAB-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-88] 반응형 모달 수정, ErrorBoundary 설정 및 디자인

src/app/academy/(workspace)/[id]/setting/components/SettingInfo/index.tsx, src/app/academy/(workspace)/[id]/setting/layout.tsx, src/app/academy/(workspace)/[id]/setting/management/institution/components/EditForm/index.tsx, src/shared/hooks/academy/useGetInfiniteAcademyList.ts
=> [CRAB-94] 기관정보 수정 후 navbar에 수정정보 반영

src/app/academy/(workspace)/[id]/dashboard/create/components/Last.tsx, src/app/academy/(workspace)/[id]/market/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx, src/app/academy/(workspace)/[id]/market/components/Release/First.tsx, src/app/academy/(workspace)/[id]/market/components/Release/Second.tsx, src/shared/components/Footer/index.tsx, src/shared/components/Input/index.tsx, src/shared/components/SelectDropdown/index.tsx, src/shared/components/Textarea/index.tsx, src/shared/utils/schema.ts, tailwind.config.ts
#225 
- focus 되었을때 효과를 원하셔서 추가하였습니다.
=> [CRAB-93] 마켓 챌린지 배포 오류 수정 

src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx, src/features/main/components/ServiceModal/index.tsx
> 추가하려는 기능에 대해 설명해주세요!
[CRAB-96] 1차 출시 관련 QA 수정
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
> 해당 기능이 개발될 브랜치 명을 알려주세요!
[CRAB-96] 세부 디테일 고치기
- 챌린지 인증 게시글 (파일 뷰어 제거) 이미지만 일단 보이게 설정.
- 구글 로그인 제거 (추후 출시시 도입) 
-  파일 뷰어 추가
[CRAB-96]: https://craftyourhabit.atlassian.net/browse/CRAB-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRAB-96]: https://craftyourhabit.atlassian.net/browse/CRAB-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-96] 1차 출시 관련 QA 수정

src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeEditForm/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/ChallengeStatistics/index.tsx, src/app/api/challenge/detail/route.ts, src/app/api/challenge/route.ts, src/shared/apis/challenge.ts, src/shared/components/FallbackMessage/index.tsx, src/shared/constants/query-keys.ts, src/shared/hooks/challenge/useEditChallenge.ts, src/shared/hooks/challenge/useGetChallengeDetail.ts, src/shared/types/acadmy.ts, src/shared/utils/schema.ts
#236 
저는 학생이 시작전 인 상황일때는 수정이 되는 것으로 알고있었는데, 서버에서 시작전인 학생임에도 
학생 데이터가 들어가있는 경우 수정하지 못하는 오류가 떠서 일단은 
학생이 있을 경우 수정하지 못하는 것을 인지할 수 있도록 모달을 띄웠습니다.
=> [CRAB-98] 챌린지 수정

src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContents/index.tsx, src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx, src/app/academy/(workspace)/[id]/feed/components/CommentForm/index.tsx, src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx, src/shared/utils/timeForToday.ts
#241 
- 탈퇴/강퇴 당한 사람을 모두 "탈퇴한 회원" 으로 표기하였습니다.
- 탈퇴한 회원의 댓글은 신고 아이콘을 제외하고 차단/대댓글은 달 수 있도록 아이콘 표기 하였습니다. 
- 인증글/댓글은 한달까지만 ~일 전/ ~ 분 전/ 약 ~시간 전 으로 표기되고 한달 이후에는 날짜로 표기됩니다.
=> [CRAB-100] 댓글 오류 처리 및 날짜 적용

src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx
#244 
ssr로 불러온 데이터는 2024-12-07로 표기 
클라에서 불러온 데이터는 한달 전까지는 ~일 전/ ~분 전 등으로 표기, 한달 이후는 ssr과 동일
=> [CRAB-101] 날짜 적용 오류 수정

src/features/main/components/UserMenu/index.tsx, src/shared/hooks/invitation/useEnrollInvitation.ts
=> [CRAB-103] 기관 초대코드 입력 후 경로 변경

src/app/my/components/invitation-modal/index.tsx
=> [CRAB-105] 초대코드 실패시 클릭 오류

package.json, src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/MyChallengeContentForm/index.tsx, src/app/academy/(workspace)/[id]/dashboard/create/components/First.tsx, src/app/academy/(workspace)/[id]/dashboard/create/components/Second.tsx, src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx, src/app/academy/(workspace)/[id]/setting/components/InstitutionProfileForm/index.tsx, src/app/academy/(workspace)/[id]/setting/management/institution/components/EditForm/index.tsx, src/app/academy/(workspace)/[id]/setting/management/invitation/components/Invitation/index.tsx, src/app/api/academy/member/count/route.ts, src/app/api/image/upload/route.ts, src/app/profile/components/ProfileEditForm/index.tsx, src/shared/apis/academy.ts, src/shared/constants/query-keys.ts, src/shared/hooks/academy/useGetAcademyMember.ts, src/shared/hooks/images/use-get-presigned-url.ts, src/shared/types/acadmy.ts, src/shared/types/image.ts, yarn.lock
[CRAB-107] 1차 출시 이전 QA 반영
[CRAB-107]: https://craftyourhabit.atlassian.net/browse/CRAB-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-107] 1차 출시 이전 QA 반영

src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContents/index.tsx, src/app/academy/(workspace)/[id]/market/page.tsx, src/app/my/components/invitation-modal/index.tsx
=> [CRAB-108] 1차 QA 반영사항 수정

src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx, src/app/academy/(workspace)/[id]/setting/management/invitation/components/Invitation/index.tsx
[CRAB-111]
[CRAB-111]: https://craftyourhabit.atlassian.net/browse/CRAB-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-111] 1차 출시 이전 QA 수정

src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx, src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx, src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx, src/app/academy/(workspace)/[id]/setting/layout.tsx, src/app/academy/(workspace)/[id]/setting/management/institution/components/InstitutionEdit/index.tsx, src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx, src/app/profile/components/EmailForm/index.tsx, src/app/profile/components/PasswordForm/index.tsx, src/app/profile/components/ProfileEdit/index.tsx, src/app/profile/components/ProfileEditForm/index.tsx, src/app/profile/components/Sidebar/index.tsx, src/app/profile/layout.tsx, src/app/profile/page.tsx, src/app/profile/password/page.tsx, src/features/academy/(workspace)/utils/challengeState.ts, src/shared/apis/challenge.ts, src/shared/constants/tab-menu.ts, src/shared/hooks/challenge/useGetInfiniteMyAcademyChallenge.ts, src/shared/hooks/market/useReleaseChallenge.ts, src/shared/utils/schema.ts
=> [CRAB-112] 마이페이지 수정 

src/app/academy/(workspace)/[id]/dashboard/components/(principal)/DashBoardUI/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx, src/app/academy/(workspace)/[id]/dashboard/page.tsx, src/app/api/challenge/list/route.ts, src/app/my/components/academy-list/index.tsx, src/shared/apis/academy.ts, src/shared/hooks/challenge/useGetInfiniteMyAcademyChallenge.ts, src/shared/types/acadmy.ts
[CRAB-113] 챌린지 전체보기 카테고리 추가
[CRAB-113]: https://craftyourhabit.atlassian.net/browse/CRAB-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-113] 챌린지 전체보기 카테고리 추가

src/app/academy/(workspace)/[id]/dashboard/components/StudentCard/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentCardList/index.tsx, src/shared/hooks/challenge/useApprovalChallenge.ts
=> [CRAB-114] 챌린지 인증글 반려 추가

src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
=> [CRAB-117] 학생 인증글 관련 에러 수정

src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx, src/app/academy/(workspace)/[id]/market/page.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
=> [CRAB-119] 챌린지 마켓 레이아웃 오류 수정 및 모달 수정

src/features/main/components/LoginModal/index.tsx, src/features/main/components/UserMenu/index.tsx
[CRAB-123] 학원 로그인 뷰 수정
[CRAB-123]: https://craftyourhabit.atlassian.net/browse/CRAB-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRAB-123] 학원 로그인 뷰 수정

src/app/pricing/page.tsx, src/features/pricing/component/PricingBox/index.tsx, src/shared/components/FramerScale/index.tsx, src/shared/constants/pricing.ts
=> [CRAB-124] 챌린지 요금제 내용 추가

src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx, src/app/card/page.tsx, src/app/space/enroll/page.tsx, src/features/card/components/CardApply/index.tsx, src/features/card/components/CardInfo/index.tsx, src/features/main/components/LoginModal/index.tsx, src/shared/components/SmallModal/index.tsx, src/shared/constants/card.ts
=> [CRAB-126] 장학카드 신청하기 

src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx, src/app/academy/(workspace)/[id]/feed/components/CommentList/index.tsx, src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx, src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx, src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx, src/app/academy/(workspace)/[id]/setting/management/instructor/components/InstructorDetail/index.tsx, src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx, src/shared/components/ProfileCard/index.tsx
=> [CRAB-128] textaure로 작성된 부분 줄바꿈 처리

src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeStatusBar/ChallengeStatusBar.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx, src/features/academy/(workspace)/components/state-label/index.tsx, src/features/academy/(workspace)/utils/challengeState.ts, src/shared/components/Textarea/index.tsx, src/shared/utils/calculateChallengeDay.ts
=> [CRAB-129] 학생 인증화면 글씨크기 수정 및 DAY 연결 

src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeStatusBar/ChallengeStatusBar.tsx, src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
=> [CRAB-130] 인증바 모바일 수정

src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeFeed/index.tsx, src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx, src/shared/types/acadmy.ts
=> [CRAB-131] 챌린지 피드 수정
